### ISSUE TITLE
PNG file not open.

### ISSUE THREAD

**Issue by Vismanto** [graphics32/GR32PNG#2]
![lnk_00350](https://user-images.githubusercontent.com/26492614/48705594-3c445100-ec02-11e8-9c59-355579876671.png)

**Comment by CWBudde** [comment]
What is the problem in particular? It seems to open and display fine on my computer.

**Comment by Vismanto** [comment]
Unzip Demo.png and test with PNG_GR32_Demo.exe
[Demo.zip](https://github.com/graphics32/GR32PNG/files/2600695/Demo.zip)

Compile and test with Delphi2007 :
    with TPortableNetworkGraphic32.Create do
      try
        LoadFromFile('Demo.png');    //Ok
        AssignTo(ImageDisplay.Bitmap);   // the program hangs up 
      finally
        Free;
      end

**Comment by Vismanto** [comment]
Problem fixed with this:

File: GR32_PortableNetworkGraphic.pas
From Line: 1427

> 

    while ZStreamRecord.avail_in > 0 do
    begin
      ZStreamRecord.next_out := TempBuffer;
      ZStreamRecord.avail_out := CBufferSize;

      inflate(ZStreamRecord, Z_NO_FLUSH);

[+]         if CBufferSize = ZStreamRecord.avail_out then break;

      Output.Write(TempBuffer^, CBufferSize - ZStreamRecord.avail_out);
    end;

>

**Comment by Vismanto** [comment]
or better:

File: GR32_PortableNetworkGraphic.pas
From Line: 1426

```
try
+ ZResult := Z_OK;
+ while (ZStreamRecord.avail_in > 0) and (ZResult = Z_OK) do
   begin
     ZStreamRecord.next_out := TempBuffer;
     ZStreamRecord.avail_out := CBufferSize;

+    ZResult := inflate(ZStreamRecord, Z_NO_FLUSH);

     Output.Write(TempBuffer^, CBufferSize - ZStreamRecord.avail_out)
   end;

```

**Comment by CWBudde** [comment]
I fixed this in the last commit (forgot to link it to this report, sorry)
