### ISSUE TITLE
Integration GR32

### ISSUE THREAD

**Issue by Vismanto** [graphics32/GR32PNG#3]
File:  GR32_PNG_Core_Integration.diff

Add to LoadFromFile

```
procedure TCustomBitmap32.LoadFromFile(const FileName: string);
var
  FileStream: TFileStream;
  Header: TBmpHeader;
  P: TPicture;
begin
  FileStream := TFileStream.Create(Filename, fmOpenRead);
  try
+  {$IFDEF UseGR32PNG}
+   if TPortableNetworkGraphic32.CanLoad(FileStream) then
+    begin
+     LoadFromStream(FileStream);
+     Exit;
+    end;
+  {$ENDIF}
    FileStream.ReadBuffer(Header, SizeOf(TBmpHeader));

```

**Comment by CWBudde** [comment]
Sounds useful. However, I'm not sure whether the diff file is still useful with GIT as it was created with the former SVN. In my case I needed to check out via SVN, patch the GR32 file, add the snippet and create a patch file again. This ended up in changing the revision as well (eventually causing some other effects).
